from authentication.models import User
from main.models import Country, Goal, Indicator

def main():
    # get country
    country = Country.objects.all()[0]
    # print(country)
    # print(User.objects.all().last())
    user = User.objects.all().last()
    # add goal
    goal_1 = Goal(goal_number=1, goal_name="1. End poverty in all its forms everywhere", goal_country=country, recorded_by=user)
    goal_1.save()
    goal_2 = Goal(goal_number=2, goal_name="2. End hunger, achieve food security and improved nutrition and promote sustainable agriculture", goal_country=country, recorded_by=user)
    goal_2.save()
    goal_3 = Goal(goal_number=3, goal_name="3. Ensure healthy lives and promote well-being for all at all ages", goal_country=country, recorded_by=user)
    goal_3.save()
    goal_4 = Goal(goal_number=4, goal_name="4. Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all", goal_country=country, recorded_by=user)
    goal_4.save()
    goal_5 = Goal(goal_number=5, goal_name="5. Achieve gender equality and empower all and girls", goal_country=country, recorded_by=user)
    goal_5.save()
    goal_6 = Goal(goal_number=6, goal_name="6. Ensure availability and sustainable management of water and sanitation for all", goal_country=country, recorded_by=user)
    goal_6.save()
    goal_7 = Goal(goal_number=7, goal_name="7. Ensure access to affordable, reliable, sustainable and modern energy for all", goal_country=country, recorded_by=user)
    goal_7.save()
    goal_8 = Goal(goal_number=8, goal_name="8. Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all", goal_country=country, recorded_by=user)
    goal_8.save()
    goal_9 = Goal(goal_number=9, goal_name="9. Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation", goal_country=country, recorded_by=user)
    goal_9.save()
    goal_10 = Goal(goal_number=10, goal_name="10. Reduce inequality within and among countries", goal_country=country, recorded_by=user)
    goal_10.save()
    goal_11 = Goal(goal_number=11, goal_name="11. Make cities and human settlements inclusive, safe, resilient and sustainable", goal_country=country, recorded_by=user)
    goal_11.save()
    goal_12 = Goal(goal_number=12, goal_name="12. Ensure sustainable consumption and production patterns", goal_country=country, recorded_by=user)
    goal_12.save()
    goal_13 = Goal(goal_number=13, goal_name="13. Take urgent action to combat climate change and its impacts", goal_country=country, recorded_by=user)
    goal_13.save()
    goal_14 = Goal(goal_number=14, goal_name="14. Conserve and sustainably use the oceans, seas and marine resources for sustainable development", goal_country=country, recorded_by=user)
    goal_14.save()
    goal_15 = Goal(goal_number=15, goal_name="15. Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss", goal_country=country, recorded_by=user)
    goal_15.save()
    goal_16 = Goal(goal_number=16, goal_name="16. Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels", goal_country=country, recorded_by=user)
    goal_16.save()
    goal_17 = Goal(goal_number=17, goal_name="17. Strengthen the means of implementation and revitalize the global partnership for sustainable development", goal_country=country, recorded_by=user)
    goal_17.save()
    print("Goals added successfully")

    # add indicator
    indicator_1_1 = Indicator(indicator_name="1.1 Proportion of population living below the national poverty line", indicator_goal=goal_1, indicator_description="Proportion of population living below the national poverty", long_term_objective="By 2030, reduce at least by half the proportion", recorded_by=user)
    indicator_1_1.save()
    indicator_1_2 = Indicator(indicator_name="1.2 Proportion of population covered by social protection systems (proportion of population covered under Rural PSNP) %", indicator_goal=goal_1, indicator_description="Proportion of population covered by social protection systems", long_term_objective="By 2030, ensure that", recorded_by=user)
    indicator_1_2.save()
    indicator_1_3 = Indicator(indicator_name="1.3 Proportion of total adult population with secure tenure rights to land, with legally recognized documentation", indicator_goal=goal_1, indicator_description="Proportion of population living below the national poverty", long_term_objective="By 2030, reduce at least by half the proportion", recorded_by=user)
    indicator_1_3.save()
    indicator_1_4 = Indicator(indicator_name="1.4 Number of household heads issued second level of land certification (millions)", indicator_goal=goal_1, indicator_description="Number of household heads issued second level of land certification", long_term_objective="By 2030, ensure that", recorded_by=user)
    indicator_1_4.save()
    indicator_1_5 = Indicator(indicator_name="1.5 Proportion of total government spending on health", indicator_goal=goal_1, indicator_description="Proportion of total government spending on health", long_term_objective="By 2030, reduce at least by half the proportion", recorded_by=user)
    indicator_1_5.save()
    indicator_1_6 = Indicator(indicator_name="1.6 Proportion of total government spending on essential services, education", indicator_goal=goal_1, indicator_description="Proportion of total government spending on essential services, education", long_term_objective="By 2030, ensure that", recorded_by=user)
    indicator_1_6.save()
    indicator_1_7 = Indicator(indicator_name="1.7 Proportion of government spending on pro-poor sectors", indicator_goal=goal_1, indicator_description="Proportion of government spending on pro-poor sectors", long_term_objective="By 2030, reduce at least by half the proportion", recorded_by=user)
    indicator_1_7.save()
    print("Indicator 1 added successfully")

    indicator_2_1 = Indicator(indicator_name="2.1 Agricultural sector value addition growth rate (%)", indicator_goal=goal_2, indicator_description="Agricultural sector value addition growth rate (%)", long_term_objective="By 2030, increase the agricultural sector value addition growth rate", recorded_by=user)
    indicator_2_1.save()
    indicator_2_2 = Indicator(indicator_name="2.2 Proportion of population with access to basic sanitation services", indicator_goal=goal_2, indicator_description="Proportion of population with access to basic sanitation services", long_term_objective="By 2030, ensure access to adequate and equitable sanitation and hygiene for all and end open defecation", recorded_by=user)
    indicator_2_2.save()
    indicator_2_3 = Indicator(indicator_name="2.3 Prevalence of moderate or severe food insecurity in the population, based on the Food Insecurity Experience Scale (FIES)- Number of beneficiaries covered by direct cash transfer Support (million) in rural areas", indicator_goal=goal_2, indicator_description="Prevalence of moderate or severe food insecurity in the population, based on the Food Insecurity Experience Scale (FIES)- Number of beneficiaries covered by direct cash transfer Support (million) in rural areas", long_term_objective="By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round", recorded_by=user)
    indicator_2_3.save()
    indicator_2_4 = Indicator(indicator_name="2.4 Proportion of children stunted", indicator_goal=goal_2, indicator_description="Proportion of children stunted", long_term_objective="By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round", recorded_by=user)
    indicator_2_4.save()
    indicator_2_5 = Indicator(indicator_name="2.5 Proportion of children wasted", indicator_goal=goal_2, indicator_description="Proportion of children wasted", long_term_objective="By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round", recorded_by=user)
    indicator_2_5.save()
    indicator_2_6 = Indicator(indicator_name="2.6 Proportion of women aged 15-49 years with anemia", indicator_goal=goal_2, indicator_description="Proportion of women", long_term_objective="By 2030, reduce ...", recorded_by=user)
    indicator_2_6.save()
    indicator_2_7 = Indicator(indicator_name="2.7 Production of major food crops million quintal", indicator_goal=goal_2, indicator_description="Production of major food crops million quintal", long_term_objective="By 2030, increase the agricultural sector value addition growth rate", recorded_by=user)
    indicator_2_7.save()
    indicator_2_8 = Indicator(indicator_name="2.8 Production of major food crops in mhere season by smallholders (in million quintals)", indicator_goal=goal_2, indicator_description="Production of major food crops in mhere season by smallholders (in million quintals)", long_term_objective="By 2030, increase the agricultural sector value addition growth rate", recorded_by=user)
    indicator_2_8.save()
    indicator_2_9 = Indicator(indicator_name="2.9 Average major food crops productivity (quintal/ha) of meher season by smallholders.", indicator_goal=goal_2, indicator_description="Average major food crops productivity (quintal/ha) of meher season by smallholders.", long_term_objective="By 2030, increase the agricultural sector value addition growth rate", recorded_by=user)
    indicator_2_9.save()
    indicator_2_10 = Indicator(indicator_name="2.10 Share of genetically improved breeds to total livestock (%)", indicator_goal=goal_2, indicator_description="Share of genetically improved breeds to total livestock (%)", long_term_objective="By 2030, increase the agricultural sector value addition growth rate", recorded_by=user)
    indicator_2_10.save()
    print("Indicator 2 added successfully")
    
    # SDG 3 Ensure healthy lives and promote well-being for all at all ages
    indicator_3_1 = Indicator(indicator_name="3.1 Maternal Mortality Ratio", indicator_goal=goal_3, indicator_description="Maternal Mortality Ratio", long_term_objective="By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births", recorded_by=user)
    indicator_3_1.save()
    indicator_3_2 = Indicator(indicator_name="3.2 Antenatal care coverage (4 times)", indicator_goal=goal_3, indicator_description="Antenatal care coverage (4 times)", long_term_objective="By 2030, ensure universal access to sexual and reproductive health-care services, including for family planning, information and education, and the integration of reproductive health into national strategies and programmes", recorded_by=user)
    indicator_3_2.save()
    indicator_3_3 = Indicator(indicator_name="3.3 Early Postnatal care coverage", indicator_goal=goal_3, indicator_description="Early Postnatal care coverage", long_term_objective="By 2030, increase the number", recorded_by=user)
    indicator_3_3.save()
    indicator_3_4 = Indicator(indicator_name="3.4 Proportion of births attended by skilled health personnel", indicator_goal=goal_3, indicator_description="Proportion of births attended by skilled health personnel", long_term_objective="By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births", recorded_by=user)
    indicator_3_4.save()
    indicator_3_5 = Indicator(indicator_name="3.5 Proportion of women married or in a union of reproductive age (aged 15-49 years) who have their need for family planning satisfied with modern methods (Percentage of currently married women currently using a contraceptive method", indicator_goal=goal_3, indicator_description="Proportion of women married or in a union of reproductive age (aged 15-49 years) who have their need for family planning satisfied with modern methods (Percentage of currently married women currently using a contraceptive method", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_5.save()
    indicator_3_6 = Indicator(indicator_name="3.6 Contraceptive prevalence rate", indicator_goal=goal_3, indicator_description="Contraceptive prevalence rate", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_6.save()
    indicator_3_7 = Indicator(indicator_name="3.7 Adolescent birth rate (per 1,000 women aged 15-19 years)", indicator_goal=goal_3, indicator_description="Adolescent birth rate (per 1,000 women aged 15-19 years)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_7.save()
    indicator_3_8 = Indicator(indicator_name="3.8 Neonatal mortality rate", indicator_goal=goal_3, indicator_description="Neonatal mortality rate", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_8.save()
    indicator_3_9 = Indicator(indicator_name="3.9 Under-five mortality rate", indicator_goal=goal_3, indicator_description="Under-five mortality rate", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_9.save()
    indicator_3_10 = Indicator(indicator_name="3.10 Number of new HIV infections per 1,000 uninfected population", indicator_goal=goal_3, indicator_description="Number of new HIV infections per 1,000 uninfected population", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_10.save()
    indicator_3_11 = Indicator(indicator_name="3.11 Tuberculosis incidence per 100,000 population", indicator_goal=goal_3, indicator_description="Tuberculosis incidence per 100,000 population", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_11.save()
    indicator_3_12 = Indicator(indicator_name="3.12 TB detection rate (%)", indicator_goal=goal_3, indicator_description="TB detection rate (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_12.save()
    indicator_3_13 = Indicator(indicator_name="3.13 TB Treatment Success rate", indicator_goal=goal_3, indicator_description="TB Treatment Success rate", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_13.save()
    indicator_3_14 = Indicator(indicator_name="3.14 Malaria incidence per 1,000 population at risk", indicator_goal=goal_3, indicator_description="Malaria incidence per 1,000 population at risk", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_14.save()
    indicator_3_15 = Indicator(indicator_name="3.15 Malaria case fatality rate (%) (Death rate due to malaria per 100,000)", indicator_goal=goal_3, indicator_description="Malaria case fatality rate (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_15.save()
    indicator_3_16 = Indicator(indicator_name="3.16 Number of people requiring interventions against neglected tropical diseases (million)", indicator_goal=goal_3, indicator_description="Number of people requiring interventions against neglected tropical diseases (million)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_16.save()
    indicator_3_17 = Indicator(indicator_name="3.17 Death rate due to road traffic injuries (Number of fatalities per 10,000 vehicles)", indicator_goal=goal_3, indicator_description="Death rate due to road traffic injuries (Number of fatalities per 10,000 vehicles)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_17.save()
    indicator_3_18 = Indicator(indicator_name="3.18 Proportion of the target population with access to 3 doses of diphtheria-tetanus-pertussis (DTP3)", indicator_goal=goal_3, indicator_description="Proportion of the target population with access to 3 doses of diphtheria-tetanus-pertussis (DTP3)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_18.save()
    indicator_3_19 = Indicator(indicator_name="3.19 Proportion of the target population with access to measles-containing vaccine (MCV1)", indicator_goal=goal_3, indicator_description="Proportion of the target population with access to measles-containing vaccine (MCV1)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_19.save()
    indicator_3_20 = Indicator(indicator_name="3.20 Proportion of the target population with access to measles-containing-vaccine second-dose (MCV2)", indicator_goal=goal_3, indicator_description="Proportion of the target population with access to measles-containing-vaccine second-dose (MCV2)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_20.save()
    indicator_3_21 = Indicator(indicator_name="3.21 Proportion of the target population with access to pneumococcal conjugate 3rd dose (PCV3)", indicator_goal=goal_3, indicator_description="Proportion of the target population with access to pneumococcal conjugate 3rd dose (PCV3)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_21.save()
    indicator_3_22 = Indicator(indicator_name="3.22 Availability of essential medicines (percent at health facilities)", indicator_goal=goal_3, indicator_description="Availability of essential medicines (percent at health facilities)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_22.save()
    indicator_3_23 = Indicator(indicator_name="3.23 Health worker density (health professional-physician, nurse and midwives to population ratio)", indicator_goal=goal_3, indicator_description="Health worker density (health professional-physician, nurse and midwives to population ratio)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_23.save()
    indicator_3_24 = Indicator(indicator_name="3.24 Health worker density (health professional-physician to population ratio)", indicator_goal=goal_3, indicator_description="Health worker density (health professional –physician to population ratio)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_3_24.save()
    print("Indicator 3 added successfully") 

    # SDG 4 - Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all
    indicator_4_1 = Indicator(indicator_name="4.1 Adult And Non-Formal Education (million)", indicator_goal=goal_4, indicator_description="Adult And Non-Formal Education (million)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_1.save()
    indicator_4_2 = Indicator(indicator_name="4.2 Grade 5 completion rate (%)", indicator_goal=goal_4, indicator_description="Grade 5 completion rate (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_2.save()
    indicator_4_3 = Indicator(indicator_name="4.3 Grade 5 completion rate (Male)", indicator_goal=goal_4, indicator_description="Grade 5 completion rate (Male)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_3.save()
    indicator_4_4 = Indicator(indicator_name="4.4 Grade 5 completion rate (Female)", indicator_goal=goal_4, indicator_description="Grade 5 completion rate (Female)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_4.save()
    indicator_4_5 = Indicator(indicator_name="4.5 Grade 8 completion rate (%)", indicator_goal=goal_4, indicator_description="Grade 8 completion rate (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_5.save()
    indicator_4_6 = Indicator(indicator_name="4.6 Grade 8 completion rate (Male)", indicator_goal=goal_4, indicator_description="Grade 8 completion rate (Male)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_6.save()
    indicator_4_7 = Indicator(indicator_name="4.7 Grade 8 completion rate (Female)", indicator_goal=goal_4, indicator_description="Grade 8 completion rate (Female)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_7.save()
    indicator_4_8 = Indicator(indicator_name="4.8 Pre-primary education gross enrollment rate (%)", indicator_goal=goal_4, indicator_description="Pre-primary education gross enrollment rate (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_8.save()
    indicator_4_9 = Indicator(indicator_name="4.9 Primary education gross enrollment rate (Male) (%)", indicator_goal=goal_4, indicator_description="Primary education gross enrollment rate (Male) (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_9.save()
    indicator_4_10 = Indicator(indicator_name="4.10 Primary education gross enrollment rate (Female) (%)", indicator_goal=goal_4, indicator_description="Primary education gross enrollment rate (Female) (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_10.save()
    indicator_4_11 = Indicator(indicator_name="4.11 Primary education (1-8) GER", indicator_goal=goal_4, indicator_description="Primary education (1-8) GER", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_11.save()
    indicator_4_12 = Indicator(indicator_name="4.12 Primary education (1-8) GER (%) Male)", indicator_goal=goal_4, indicator_description="Primary education (1-8) GER (%) Male)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_12.save()
    indicator_4_13 = Indicator(indicator_name="4.13 Primary education (1-8) GER (%) Female)", indicator_goal=goal_4, indicator_description="Primary education (1-8) GER (%) Female)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_13.save()
    indicator_4_14 = Indicator(indicator_name="4.14 Primary education (1-8) NER", indicator_goal=goal_4, indicator_description="Primary education (1-8) NER", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_14.save()
    indicator_4_15 = Indicator(indicator_name="4.15 Primary education (1-8) NER (%) Male)", indicator_goal=goal_4, indicator_description="Primary education (1-8) NER (%) Male)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_15.save()
    indicator_4_16 = Indicator(indicator_name="4.16 Primary education (1-8) NER (%) Female)", indicator_goal=goal_4, indicator_description="Primary education (1-8) NER (%) Female)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_16.save()
    indicator_4_17 = Indicator(indicator_name="4.17 Secondary education (1-8) GER", indicator_goal=goal_4, indicator_description="Secondary education (1-8) GER", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_17.save()
    indicator_4_18 = Indicator(indicator_name="4.18 Secondary education (1-8) GER (%) Male)", indicator_goal=goal_4, indicator_description="Secondary education (1-8) GER (%) Male)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_18.save()
    indicator_4_19 = Indicator(indicator_name="4.19 Secondary education (1-8) GER (%) Female)", indicator_goal=goal_4, indicator_description="Secondary education (1-8) GER (%) Female)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_19.save()
    indicator_4_20 = Indicator(indicator_name="4.20 Secondary education (1-8) NER", indicator_goal=goal_4, indicator_description="Secondary education (1-8) NER", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_20.save()
    indicator_4_21 = Indicator(indicator_name="4.21 Secondary education (1-8) NER (%) Male)", indicator_goal=goal_4, indicator_description="Secondary education (1-8) NER (%) Male)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_21.save()
    indicator_4_22 = Indicator(indicator_name="4.22 Secondary education (1-8) NER (%) Female)", indicator_goal=goal_4, indicator_description="Secondary education (1-8) NER (%) Female)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_22.save()
    indicator_4_23 = Indicator(indicator_name="4.23 Undergraduate enrolment in all programs (in number) (Total)", indicator_goal=goal_4, indicator_description="Undergraduate enrolment in all programs (in number) (Total)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_23.save()
    indicator_4_24 = Indicator(indicator_name="4.24 Share of female Undergraduate enrolment in all programs (%)", indicator_goal=goal_4, indicator_description="Share of female Undergraduate enrolment in all programs (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_24.save()
    indicator_4_25 = Indicator(indicator_name="4.25 Postgraduate (2nd degree) enrolment in all programs (in number (Total)", indicator_goal=goal_4, indicator_description="Postgraduate (2nd degree) enrolment in all programs (in number (Total)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_25.save()
    indicator_4_26 = Indicator(indicator_name="4.26 Share of female in Postgraduate (2nd degree) enrolment (%)", indicator_goal=goal_4, indicator_description="Share of female in Postgraduate (2nd degree) enrolment (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_26.save()
    indicator_4_27 = Indicator(indicator_name="4.27 Total number of PhD degree enrolment", indicator_goal=goal_4, indicator_description="Total number of PhD degree enrolment", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_27.save()
    indicator_4_28 = Indicator(indicator_name="4.28 Proportion of youth and adults in Enrolled in TVET (thousands)", indicator_goal=goal_4, indicator_description="Proportion of youth and adults in Enrolled in TVET (thousands)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_28.save()
    indicator_4_29 = Indicator(indicator_name="4.29 Gender Parity index (GPI) in Pre-primary (index)", indicator_goal=goal_4, indicator_description="Gender Parity index (GPI) in Pre-primary (index)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_29.save()
    indicator_4_30 = Indicator(indicator_name="4.30 Gender Parity index (GPI) in Grades 1-8 (index)", indicator_goal=goal_4, indicator_description="Gender Parity index (GPI) in Grades 1-8 (index)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_30.save()
    indicator_4_31 = Indicator(indicator_name="4.31 Gender Parity index (GPI) in Grades 9-12 (index)", indicator_goal=goal_4, indicator_description="Gender Parity index (GPI) in Grades 9-12 (index)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_31.save()
    indicator_4_32 = Indicator(indicator_name="4.32 Proportion of schools with access to electricity (primary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to electricity (primary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_32.save()
    indicator_4_33 = Indicator(indicator_name="4.33 Proportion of schools with access to electricity (secondary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to electricity (secondary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_33.save()
    indicator_4_34 = Indicator(indicator_name="4.34 Proportion of schools with access to basic drinking water(primary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to basic drinking water(primary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_34.save()
    indicator_4_35 = Indicator(indicator_name="4.35 Proportion of schools with access to basic drinking water(secondary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to basic drinking water(secondary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_35.save()
    indicator_4_36 = Indicator(indicator_name="4.36 Proportion of schools with basic hand washing facilities (primary)", indicator_goal=goal_4, indicator_description="Proportion of schools with basic hand washing facilities (primary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_36.save()
    indicator_4_37 = Indicator(indicator_name="4.37 Proportion of schools with basic hand washing facilities (secondary)", indicator_goal=goal_4, indicator_description="Proportion of schools with basic hand washing facilities (secondary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_37.save()
    indicator_4_38 = Indicator(indicator_name="4.38 Proportion of schools with access to single-sex basic sanitation (primary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to single-sex basic sanitation (primary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_38.save()
    indicator_4_39 = Indicator(indicator_name="4.39 Proportion of schools with access to single-sex basic sanitation (secondary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to single-sex basic sanitation (secondary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_39.save()
    indicator_4_40 = Indicator(indicator_name="4.40 Proportion of schools with access to pedagogical centers (primary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to pedagogical centers (primary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_40.save()
    indicator_4_41 = Indicator(indicator_name="4.41 Proportion of schools with access to pedagogical centers (secondary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to pedagogical centers (secondary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_41.save()
    indicator_4_42 = Indicator(indicator_name="4.42 Proportion of schools with access to computers (secondary)", indicator_goal=goal_4, indicator_description="Proportion of schools with access to pedagogical centers (secondary)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_4_42.save()
    print("Indicator 4 added successfully")

    # SDG 5 - Achieve gender equality and empower all women and girls
    indicator_5_1 = Indicator(indicator_name="5.1 Whether or not legal frameworks are in place to promote, enforce and monitor equality and non-discrimination on the basis of sex (1= yes there is, 0= no legal framework)", indicator_goal=goal_5, indicator_description="Whether or not legal frameworks are in place to promote, enforce and monitor equality and non-discrimination on the basis of sex (1= yes there is, 0= no legal framework)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_1.save()
    indicator_5_2 = Indicator(indicator_name="5.2 Proportion of ever-partnered women and girls subjected to physical and sexual violence by a current or former intimate partner in the previous 12 months", indicator_goal=goal_5, indicator_description="Proportion of ever-partnered women and girls subjected to physical and sexual violence by a current or former intimate partner in the previous 12 months", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_2.save()
    indicator_5_3 = Indicator(indicator_name="5.3 Proportion of women aged 20-24 years who were married or in a union before age 18", indicator_goal=goal_5, indicator_description="Proportion of women aged 20-24 years who were married or in a union before age 18", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_3.save()
    indicator_5_4 = Indicator(indicator_name="5.4 Proportion of girls and women aged 15-49 years who have undergone female genital mutilation/cutting", indicator_goal=goal_5, indicator_description="Proportion of girls and women aged 15-49 years who have undergone female genital mutilation/cutting", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_4.save()
    indicator_5_5 = Indicator(indicator_name="5.5 Proportion of time spent on unpaid domestic chores", indicator_goal=goal_5, indicator_description="Proportion of time spent on unpaid domestic chores", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_5.save()
    indicator_5_6 = Indicator(indicator_name="5.6 Proportion of time spent on unpaid care work", indicator_goal=goal_5, indicator_description="Proportion of time spent on unpaid care work", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_6.save()
    indicator_5_7 = Indicator(indicator_name="5.7 Number of seats held by women in national parliaments", indicator_goal=goal_5, indicator_description="Number of seats held by women in national parliaments", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_7.save()
    indicator_5_8 = Indicator(indicator_name="5.8 Proportion of women in top management level positions", indicator_goal=goal_5, indicator_description="Proportion of women in top management level positions", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_8.save()
    indicator_5_9 = Indicator(indicator_name="5.9 Proportion of women in managerial positions", indicator_goal=goal_5, indicator_description="Proportion of women in managerial positions", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_9.save()
    indicator_5_10 = Indicator(indicator_name="5.10 Proportion of women in senior and middle management positions", indicator_goal=goal_5, indicator_description="Proportion of women in senior and middle management positions", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_10.save()
    indicator_5_11 = Indicator(indicator_name="5.11 Proportion of women who make their own informed decisions regarding contraceptive use (% of women aged 15-49 years) (proportion of currently married women using modern contraceptive method)", indicator_goal=goal_5, indicator_description="Proportion of women who make their own informed decisions regarding contraceptive use (% of women aged 15-49 years) (proportion of currently married women using modern contraceptive method)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_11.save()
    indicator_5_12 = Indicator(indicator_name="5.12 Number of countries with laws and regulations that guarantee full and equal access to women and men aged 15 years and older to sexual and reproductive health care, information and education (1=yes, 0=no)", indicator_goal=goal_5, indicator_description="Number of countries with laws and regulations that guarantee full and equal access to women and men aged 15 years and older to sexual and reproductive health care, information and education (1=yes, 0=no)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_12.save()
    indicator_5_13 = Indicator(indicator_name="5.13 Proportion of individuals who own a mobile telephone", indicator_goal=goal_5, indicator_description="Proportion of individuals who own a mobile telephone", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_5_13.save()
    print("Indicator 5 added successfully")

    # SDG 6 - Ensure availability and sustainable management of water and sanitation for all
    indicator_6_1 = Indicator(indicator_name="6.1 Proportion of population using safely managed drinking water services", indicator_goal=goal_6, indicator_description="Proportion of population using safely managed drinking water services", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_6_1.save()
    indicator_6_2 = Indicator(indicator_name="6.2 Proportion of population with improved sanitation services", indicator_goal=goal_6, indicator_description="Proportion of population with improved sanitation services", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_6_2.save()
    indicator_6_3 = Indicator(indicator_name="6.3 Degree of integrated water resources management (%)", indicator_goal=goal_6, indicator_description="Degree of integrated water resources management (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_6_3.save()
    indicator_6_4 = Indicator(indicator_name="6.4 Proportion of transboundary basin area with an operational arrangement for water cooperation", indicator_goal=goal_6, indicator_description="arrangement for water cooperation arrangement for water cooperation", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_6_4.save()
    indicator_6_5 = Indicator(indicator_name="6.5 ODA flow for water supply and sanitation in million USD", indicator_goal=goal_6, indicator_description="ODA flow for water supply and sanitation in million USD", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_6_5.save()
    indicator_6_6 = Indicator(indicator_name="6.6 Proportion of local administrative units with established and operational policies and procedures for participation of local communities in water and sanitation management", indicator_goal=goal_6, indicator_description="Proportion of local administrative units with established and operational policies and procedures for participation of local communities in water and sanitation management", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_6_6.save()
    print("Indicator 6 added successfully")

    # SDG 7 - Ensure access to affordable, reliable, sustainable and modern energy for all
    indicator_7_1 = Indicator(indicator_name="7.1 Proportion of population with access to electricity", indicator_goal=goal_7, indicator_description="Proportion of population with access to electricity", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_1.save()
    indicator_7_2 = Indicator(indicator_name="7.2 Total number of customers connected with electricity (million)", indicator_goal=goal_7, indicator_description="Total number of customers connected with electricity (million)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_2.save()
    indicator_7_3 = Indicator(indicator_name="7.3 Renewable energy share in the total final energy consumption", indicator_goal=goal_7, indicator_description="Renewable energy share in the total final energy consumption (electricity generation from renewable sources)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_3.save()
    indicator_7_4 = Indicator(indicator_name="7.4 Energy intensity measured in terms of primary energy and GDP", indicator_goal=goal_7, indicator_description="Energy intensity measured in terms of primary energy and GDP (International Energy Agency)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_4.save()
    indicator_7_5 = Indicator(indicator_name="7.5 ODA flow for energy generation and supply in million USD", indicator_goal=goal_7, indicator_description="ODA flow for energy generation and supply in million USD", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_5.save()
    indicator_7_6 = Indicator(indicator_name="7.6 Installed renewable energy-generating capacity", indicator_goal=goal_7, indicator_description="Installed renewable energy-generating capacity", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_6.save()
    indicator_7_7 = Indicator(indicator_name="7.7 Electric power production (in Gigawatt Hour -GWH)", indicator_goal=goal_7, indicator_description="Electric power production (in Gigawatt Hour -GWH)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_7_7.save()
    print("Indicator 7 added successfully")

    # SDG 8 - Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all
    indicator_8_1 = Indicator(indicator_name="8.1 Annual growth rate of real GDP per-capita", indicator_goal=goal_8, indicator_description="Annual growth rate of real GDP per-capita", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_1.save()
    indicator_8_2 = Indicator(indicator_name="8.2 Annual growth rate of real GDP (%)", indicator_goal=goal_8, indicator_description="Annual growth rate of real GDP (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_2.save()
    indicator_8_3 = Indicator(indicator_name="8.3 Annual growth rate of real GDP per employed person (Compared for 2013 against 2021)", indicator_goal=goal_8, indicator_description="Annual growth rate of real GDP per employed person (Compared for 2013 against 2021)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_3.save()
    indicator_8_4 = Indicator(indicator_name="8.4 Per Capita GDP (USD) (Nominal)", indicator_goal=goal_8, indicator_description="Per Capita GDP (USD) (Nominal)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_4.save()
    indicator_8_5 = Indicator(indicator_name="8.5 Proportion of informal employment, by sector and sex (ILO harmonized estimates)", indicator_goal=goal_8, indicator_description="Proportion of informal employment, by sector and sex (ILO harmonized estimates)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_5.save()
    indicator_8_6 = Indicator(indicator_name="8.6 Total number of employed persons in million (baseline data is for 2013)", indicator_goal=goal_8, indicator_description="Total number of employed persons in million (baseline data is for 2013)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_6.save()
    indicator_8_7 = Indicator(indicator_name="8.7 Average Domestic raw material input share in food and beverage industries", indicator_goal=goal_8, indicator_description="Average Domestic raw material input share in food and beverage industries", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_7.save()
    indicator_8_8 = Indicator(indicator_name='8.8 Unemployment rate (national)', indicator_goal=goal_8, indicator_description="Unemployment rate (national)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_8.save()
    indicator_8_9 = Indicator(indicator_name="8.9 Urban unemployment rate", indicator_goal=goal_8, indicator_description="Urban unemployment rate", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_9.save()
    indicator_8_10 = Indicator(indicator_name="8.10 Proportion of youth not in education, employment or training (Proportion of urban youth unemployment rate)", indicator_goal=goal_8, indicator_description="Proportion of youth not in education, employment or training (Proportion of urban youth unemployment rate)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_10.save()
    indicator_8_11 = Indicator(indicator_name="8.11 Tourism direct GDP as a proportion of total GDP (Hotels and Restaurants value addition share in GDP 26 )", indicator_goal=goal_8, indicator_description="Tourism direct GDP as a proportion of total GDP (Hotels and Restaurants value addition share in GDP 26 )", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_11.save()
    indicator_8_12 = Indicator(indicator_name="8.12 Population per commercial bank branches", indicator_goal=goal_8, indicator_description="Population per commercial bank branches", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_12.save()
    indicator_8_13 = Indicator(indicator_name="8.13 Aid for Trade commitments and disbursements (million USD)", indicator_goal=goal_8, indicator_description="Aid for Trade commitments and disbursements (million USD)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_13.save()
    indicator_8_14 = Indicator(indicator_name="8.14 Existence of a developed and operationalized national strategy for youth employment, as a distinct strategy or as part of a national employment strategy (1= yes, 0= no)", indicator_goal=goal_8, indicator_description="Existence of a developed and operationalized national strategy for youth employment, as a distinct strategy or as part of a national employment strategy (1= yes, 0= no)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_8_14.save()
    print("Indicator 8 added successfully")
    
    # SDG 9 - Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation
    indicator_9_1 = Indicator(indicator_name="9.1 Total all weather road constructed (KM)", indicator_goal=goal_9, indicator_description="Total all weather road constructed (KM)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_1.save()
    indicator_9_2 = Indicator(indicator_name="9.2 Proportion of the rural population who live within 5 km of an all-season road", indicator_goal=goal_9, indicator_description="Proportion of the rural population who live within 5 km of an all-season road", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_2.save()
    indicator_9_3 = Indicator(indicator_name="9.3 Supply of passenger seats per flight distance (in billion km)", indicator_goal=goal_9, indicator_description="Supply of passenger seats per flight distance (in billion km)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_3.save()
    indicator_9_4 = Indicator(indicator_name="9.4 Proportion of the population with access to electricity", indicator_goal=goal_9, indicator_description="Proportion of the population with access to electricity", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_4.save()
    indicator_9_5 = Indicator(indicator_name="9.5 Number of passengers transported with international by EAL (million)", indicator_goal=goal_9, indicator_description="Number of passengers transported with international by EAL (million)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_5.save()
    indicator_9_6 = Indicator(indicator_name="9.6 Freight transported by air cargo (in thousand tons)", indicator_goal=goal_9, indicator_description="Freight transported by air cargo (in thousand tons)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_6.save()
    indicator_9_7 = Indicator(indicator_name="9.7 Freight transported by truck (millions of tons)", indicator_goal=goal_9, indicator_description="Freight transported by truck (millions of tons)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_7.save()
    indicator_9_8 = Indicator(indicator_name="9.8 Freight transported by train (millions of tons)", indicator_goal=goal_9, indicator_description="Freight transported by train (millions of tons)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_8.save()
    indicator_9_9 = Indicator(indicator_name="9.9 Share of general cargo carried by multimodal transport system (%)", indicator_goal=goal_9, indicator_description="Share of general cargo carried by multimodal transport system (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_9.save()
    indicator_9_10 = Indicator(indicator_name="9.10 Average improved logistics efficiency in numbers", indicator_goal=goal_9, indicator_description="Average improved logistics efficiency in numbers", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_10.save()
    indicator_9_11 = Indicator(indicator_name="9.11 Percentage of the civil aviation’s safety audit rank", indicator_goal=goal_9, indicator_description="Percentage of the civil aviation’s safety audit rank", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_11.save()
    indicator_9_12 = Indicator(indicator_name="9.12 Number of passengers (in millions) transported by cross-country transport vehicles", indicator_goal=goal_9, indicator_description="Number of passengers (in millions) transported by cross-country transport vehicles", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_12.save()
    indicator_9_13 = Indicator(indicator_name="9.13 Manufacturing value added growth rate (%)", indicator_goal=goal_9, indicator_description="Manufacturing value added growth rate (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_13.save()
    indicator_9_14 = Indicator(indicator_name="9.14 Manufacturing value added as a proportion of GDP", indicator_goal=goal_9, indicator_description="Manufacturing value added as a proportion of GDP", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_14.save()
    indicator_9_15 = Indicator(indicator_name="9.15 Medium and large-scale manufacturing value added as a proportion of GDP", indicator_goal=goal_9, indicator_description="Medium and large-scale manufacturing value added as a proportion of GDP", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_15.save()
    indicator_9_16 = Indicator(indicator_name="9.16 Small scale manufacturing value added as a proportion of GDP", indicator_goal=goal_9, indicator_description="Small scale manufacturing value added as a proportion of GDP", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_16.save()
    indicator_9_17 = Indicator(indicator_name="9.17 Manufacturing employment as a proportion of total employment", indicator_goal=goal_9, indicator_description="Manufacturing employment as a proportion of total employment", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_17.save()
    indicator_9_18 = Indicator(indicator_name="9.18 Proportion of small-scale industries in total industry value added (%)", indicator_goal=goal_9, indicator_description="Proportion of small-scale industries in total industry value added (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_18.save()
    indicator_9_19 = Indicator(indicator_name="9.19 The share of mass transport service in the total public transport usage of cities (%)", indicator_goal=goal_9, indicator_description="The share of mass transport service in the total public transport usage of cities (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_19.save()
    indicator_9_20 = Indicator(indicator_name="9.20 Total official international support (official development assistance plus other official flows) to infrastructure (for energy generation and supply, other social infrastructure and services, and transport and storage)", indicator_goal=goal_9, indicator_description="Total official international support (official development assistance plus other official flows) to infrastructure (for energy generation and supply, other social infrastructure and services, and transport and storage)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_20.save()
    indicator_9_21 = Indicator(indicator_name="9.21 Proportion of population covered by at least a 2G mobile network", indicator_goal=goal_9, indicator_description="(proportion of mobile customers)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_9_21.save()
    print("Indicator 9 added successfully")

    # SDG 10 - Reduce inequality within and among countries
    indicator_10_1 = Indicator(indicator_name="10.1 Proportion of rural population living below 50 per cent (bottom two wealth quantile) (Rural) (%)", indicator_goal=goal_10, indicator_description="Proportion of rural population living below 50 per cent (bottom two wealth quantile) (Rural) (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_10_1.save()
    indicator_10_2 = Indicator(indicator_name="10.2 Proportion of rural population living below 50 per cent (bottom two wealth quantile) (Urban) (%)", indicator_goal=goal_10, indicator_description="Proportion of rural population living below 50 per cent (bottom two wealth quantile) (Urban) (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_10_2.save()
    indicator_10_3 = Indicator(indicator_name="10.3 Proportion of members and voting rights of developing countries in international organizations (1= yes there is, 0= there is no)", indicator_goal=goal_10, indicator_description="Proportion of members and voting rights of developing countries in international organizations (1= yes there is, 0= there is no)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_10_3.save()
    indicator_10_4 = Indicator(indicator_name="10.4 Number of countries with migration policies that facilitate orderly, safe, regular and responsible migration and mobility of people (1= yes, 0= no)", indicator_goal=goal_10, indicator_description="Number of countries with migration policies that facilitate orderly, safe, regular and responsible migration and mobility of people (1= yes, 0= no)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_10_4.save()
    indicator_10_5 = Indicator(indicator_name="10.5 Number of people who died or disappeared in the process of migration towards an international destination", indicator_goal=goal_10, indicator_description="Number of people who died or disappeared in the process of migration towards an international destination", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_10_5.save()
    indicator_10_6 = Indicator(indicator_name="10.6 Proportion (%) of the population who are refugees", indicator_description="Proportion (%) of the population who are refugees", indicator_goal=goal_10, long_term_objective="By 2030, ...", recorded_by=user)
    indicator_10_6.save()
    print("Indicator 10 added successfully")

    # SDG 11 - Make cities and human settlements inclusive, safe, resilient and sustainable
    indicator_11_1 = Indicator(indicator_name="11.1 Proportion of urban population living in slums", indicator_goal=goal_11, indicator_description="Proportion of urban population living in slums", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_11_1.save()
    indicator_11_2 = Indicator(indicator_name="11.2 Transportation waiting time in Addis Ababa (in minutes)", indicator_goal=goal_11, indicator_description="Transportation waiting time in Addis Ababa (in minutes)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_11_2.save()
    indicator_11_3 = Indicator(indicator_name="11.3 Coverage of solid waste collection and disposal services (%)", indicator_goal=goal_11, indicator_description="Coverage of solid waste collection and disposal services (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_11_3.save()
    print("Indicator 11 added successfully")

    # SDG 12 - Ensure sustainable consumption and production patterns
    indicator_12_1 = Indicator(indicator_name="12.1 Number of countries developing, adopting or implementing policy instruments aimed at supporting the shift to sustainable consumption and production (1 = YES; 0 = NO)", indicator_goal=goal_12, indicator_description="Number of countries developing, adopting or implementing policy instruments aimed at supporting the shift to sustainable consumption and production (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_12_1.save()
    indicator_12_2 = Indicator(indicator_name="12.2 Compliance with the Basel Convention on hazardous waste and other chemicals", indicator_goal=goal_12, indicator_description="Compliance with the Basel Convention on hazardous waste and other chemicals", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_12_2.save()
    indicator_12_3 = Indicator(indicator_name="12.3 Hazardous waste generated (Tons)", indicator_goal=goal_12, indicator_description="Hazardous waste generated (Tons)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_12_3.save()
    indicator_12_4 = Indicator(indicator_name="12.4 Number of companies publishing sustainability reports", indicator_goal=goal_12, indicator_description="Number of companies publishing sustainability reports", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_12_4.save()
    indicator_12_5 = Indicator(indicator_name="12.5 Countries implementing sustainable public procurement policies and action plans (1 = YES; 0 = NO)", indicator_goal=goal_12, indicator_description="Countries implementing sustainable public procurement policies and action plans (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_12_5.save()
    print("Indicator 12 added successfully")

    # SDG 13 - Take urgent action to combat climate change and its impacts
    indicator_13_1 = Indicator(indicator_name="13.1 Countries that reported having a National Disaster and Risk Reduction (NDRR) Strategy which is aligned to the Sendai Framework to a certain extent (1 = YES; 0 = NO)", indicator_goal=goal_13, indicator_description="Countries that reported having a National Disaster and Risk Reduction (NDRR) Strategy which is aligned to the Sendai Framework to a certain extent (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_13_1.save()
    indicator_13_2 = Indicator(indicator_name="13.2 Number of countries with nationally determined contributions, long-term strategies, national adaptation plans and adaptation communications, as reported to the secretariat of the United Nations Framework Convention on Climate Change (1 = YES; 0 = NO)", indicator_goal=goal_13, indicator_description="Number of countries with nationally determined contributions, long-term strategies, national adaptation plans and adaptation communications, as reported to the secretariat of the United Nations Framework Convention on Climate Change (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_13_2.save()
    indicator_13_3 = Indicator(indicator_name="13.3 Total greenhouse gas emissions MtCO2eq per year", indicator_goal=goal_13, indicator_description="Total greenhouse gas emissions MtCO2eq per year", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_13_3.save()
    indicator_13_4 = Indicator(indicator_name="13.4 Extent to which (i) global citizenship education and (ii) education for sustainable development are mainstreamed in (a) national education policies; (b) curricula; (c) teacher education; and (d) student assessment", indicator_goal=goal_13, indicator_description="Extent to which (i) global citizenship education and (ii) education for sustainable development are mainstreamed in (a) national education policies; (b) curricula; (c) teacher education; and (d) student assessment", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_13_4.save()
    indicator_13_5 = Indicator(indicator_name="13.5 Amounts provided and mobilized in United States dollars per year in relation to the continued existing collective mobilization goal of the $100 billion commitment through to 2025 (Amount of resource mobilized in million USD)", indicator_goal=goal_13, indicator_description="Amounts provided and mobilized in United States dollars per year in relation to the continued existing collective mobilization goal of the $100 billion commitment through to 2025 (Amount of resource mobilized in million USD)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_13_5.save()
    indicator_13_6 = Indicator(indicator_name="13.6 Number of least developed countries and small island developing states with nationally determined contributions, long-term strategies, national adaptation plans and adaptation communications, as reported to the secretariat of the United Nations Framework Convention on Climate Change (1= Yes, 0 = No)", indicator_goal=goal_13, indicator_description="Number of least developed countries and small island developing states with nationally determined contributions, long-term strategies, national adaptation plans and adaptation communications, as reported to the secretariat of the United Nations Framework Convention on Climate Change (1= Yes, 0 = No)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_13_6.save()
    print("Indicator 13 added successfully")

    # SDG 14 - Conserve and sustainably use the oceans, seas and marine resources for sustainable development
    indicator_14_1 = Indicator(indicator_name="14.1 Amount of fish production in thousand metric tons", indicator_goal=goal_14, indicator_description="Amount of fish production in thousand metric tons", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_14_1.save()
    indicator_14_2 = Indicator(indicator_name="14.2 Area of water bodies (lakes, wetlands, dams, eco-hydrology, rivers, littoral zones aquifers covered under water protection rules and management systems in million hectares", indicator_goal=goal_14, indicator_description="Area of water bodies (lakes, wetlands, dams, eco-hydrology, rivers, littoral zones aquifers covered under water protection rules and management systems in million hectares", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_14_2.save()
    indicator_14_3 = Indicator(indicator_name="14.3 Sustainable fisheries as a proportion of GDP in small island developing States, least developed countries and all countries (Fishery value addition in GDG)", indicator_goal=goal_14, indicator_description="Sustainable fisheries as a proportion of GDP in small island developing States, least developed countries and all countries (Fishery value addition in GDG)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_14_3.save()
    print("Indicator 14 added successfully")

    # SDG 15 - Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification,and halt and reverse land degradation and halt biodiversity loss
    indicator_15_1 = Indicator(indicator_name="15.1 Forest area as a proportion of total land area", indicator_goal=goal_15, indicator_description="Forest area as a proportion of total land area", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_1.save()
    indicator_15_2 = Indicator(indicator_name="15.2 Area of Land Under Protection and Management System in million hectares)", indicator_goal=goal_15, indicator_description="Area of Land Under Protection and Management System in million hectares)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_2.save()
    indicator_15_3 = Indicator(indicator_name="15.3 Average proportion of Mountain Key Biodiversity Areas (KBAs) covered by protected areas (Area of community watersheds covered by biodiversity (in thousand hectares)", indicator_goal=goal_15, indicator_description="Average proportion of Mountain Key Biodiversity Areas (KBAs) covered by protected areas (Area of community watersheds covered by biodiversity (in thousand hectares)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_3.save()
    indicator_15_4 = Indicator(indicator_name="15.4 Coverage by protected areas of important sites for mountain biodiversity (Areas enclosed and protected for rehabilitation (in thousand hectares))", indicator_goal=goal_15, indicator_description="Coverage by protected areas of important sites for mountain biodiversity (Areas enclosed and protected for rehabilitation (in thousand hectares))", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_4.save()
    indicator_15_5 = Indicator(indicator_name="15.5 Integrated watershed development coverage in millions of hectares (Numbers of planned community watersheds)", indicator_goal=goal_15, indicator_description="Integrated watershed development coverage in millions of hectares (Numbers of planned community watersheds)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_5.save()
    indicator_15_6 = Indicator(indicator_name="15.6 Countries that are contracting Parties to the International Treaty on Plant Genetic Resources for Food and Agriculture (PGRFA) (1 = YES; 0 = NO)", indicator_goal=goal_15, indicator_description="Countries that are contracting Parties to the International Treaty on Plant Genetic Resources for Food and Agriculture (PGRFA) (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_6.save()
    indicator_15_7 = Indicator(indicator_name="15.7 Legislation, Regulation, Act related to the prevention of introduction", indicator_goal=goal_15, indicator_description="and management of Invasive Alien Species (1 = YES, 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_7.save()
    indicator_15_8 = Indicator(indicator_name="15.8 National Biodiversity Strategy and Action Plan (NBSAP) targets alignment to Aichi Biodiversity target 9 set out in the Strategic Plan for Biodiversity 2011-2020 (1 = YES, 0 = NO)", indicator_goal=goal_15, indicator_description="National Biodiversity Strategy and Action Plan (NBSAP) targets alignment to Aichi Biodiversity target 9 set out in the Strategic Plan for Biodiversity 2011-2020 (1 = YES, 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_15_8.save()
    print("Indicator 15 added successfully")
    
    # SDG 16 - Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels
    indicator_16_1 = Indicator(indicator_name="16.1 Proportion of population satisfied with their last experience of public services", indicator_goal=goal_16, indicator_description="Proportion of population satisfied with their last experience of public services", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_16_1.save()
    indicator_16_2 = Indicator(indicator_name="16.2 Ratio for female members of parliaments", indicator_goal=goal_16, indicator_description="Ratio for female members of parliaments", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_16_2.save()
    indicator_16_3 = Indicator(indicator_name="16.3 Proportion of children under 5 years of age whose births have been registered with a civil authority", indicator_goal=goal_16, indicator_description="Proportion of children under 5 years of age whose births have been registered with a civil authority", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_16_3.save()
    indicator_16_4 = Indicator(indicator_name="16.4 Number of countries that adopt and implement constitutional, statutory and/or policy guarantees for public access to information (1 = YES; 0 = NO)", indicator_goal=goal_16, indicator_description="Number of countries that adopt and implement constitutional, statutory and/or policy guarantees for public access to information (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_16_4.save()
    indicator_16_5 = Indicator(indicator_name="16.5 Countries with National Human Rights Institutions in compliance with the Paris Principles, A status (1 = YES; 0 = NO)", indicator_goal=goal_16, indicator_description="Countries with National Human Rights Institutions in compliance with the Paris Principles, A status (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_16_5.save()
    print("Indicator 16 added successfully")

    # SDG 17 - Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development.
    indicator_17_1 = Indicator(indicator_name="17.1 Total government revenue as a proportion of GDP", indicator_goal=goal_17, indicator_description="Total government revenue as a proportion of GDP", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_1.save()
    indicator_17_2 = Indicator(indicator_name="17.2 Proportion of taxes to GDP (%)", indicator_goal=goal_17, indicator_description="Proportion of taxes to GDP (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_2.save()
    indicator_17_3 = Indicator(indicator_name="17.3 Proportion of domestic budget funded by domestic taxes (%)", indicator_goal=goal_17, indicator_description="Proportion of domestic budget funded by domestic taxes (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_3.save()
    indicator_17_4 = Indicator(indicator_name="17.4 Foreign direct investment (FDI) inflows (million USD)", indicator_goal=goal_17, indicator_description="Foreign direct investment (FDI) inflows (million USD)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_4.save()
    indicator_17_5 = Indicator(indicator_name="17.5 Share of FDI to total domestic investment (Gross Capital Formation) (%)", indicator_goal=goal_17, indicator_description="Share of FDI to total domestic investment (Gross Capital Formation) (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_5.save()
    indicator_17_6 = Indicator(indicator_name="17.6 Foreign direct investment as a proportion of gross national income", indicator_goal=goal_17, indicator_description="Foreign direct investment as a proportion of gross national income", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_6.save()
    indicator_17_7 = Indicator(indicator_name="17.7 official development assistance flow in million USD", indicator_goal=goal_17, indicator_description="official development assistance flow in million USD", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_7.save()
    indicator_17_8 = Indicator(indicator_name="17.8 official development assistance as a proportion of gross national income", indicator_goal=goal_17, indicator_description="official development assistance as a proportion of gross national income", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_8.save()
    indicator_17_9 = Indicator(indicator_name="17.9 Volume of remittances (in United States dollars) as a proportion of total GDP", indicator_goal=goal_17, indicator_description="Volume of remittances (in United States dollars) as a proportion of total GDP", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_9.save()
    indicator_17_10 = Indicator(indicator_name="17.10 Debt service as a proportion of exports of goods and services (%)", indicator_goal=goal_17, indicator_description="Debt service as a proportion of exports of goods and services (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_10.save()
    indicator_17_11 = Indicator(indicator_name="17.11 Debt service as a proportion of merchandize export (%)", indicator_goal=goal_17, indicator_description="Debt service as a proportion of merchandize export (%)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_11.save()
    indicator_17_12 = Indicator(indicator_name="17.12 Existence of investment promotion (1=Yes, 0= no)", indicator_goal=goal_17, indicator_description="Existence of investment promotion (1=Yes, 0= no)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_12.save()
    indicator_17_13 = Indicator(indicator_name="17.13 Fixed broadband subscriptions per 100 inhabitants", indicator_goal=goal_17, indicator_description="Fixed broadband subscriptions per 100 inhabitants", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_13.save()
    indicator_17_14 = Indicator(indicator_name="17.14 Proportion of individuals using the Internet (access to internet)", indicator_goal=goal_17, indicator_description="Proportion of individuals using the Internet (access to internet)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_14.save()
    indicator_17_15 = Indicator(indicator_name="17.15 Ethiopia's weighted tariff-average", indicator_goal=goal_17, indicator_description="Ethiopia's weighted tariff-average", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_15.save()
    indicator_17_16 = Indicator(indicator_name="17.16 Merchandize export earning in million USD", indicator_goal=goal_17, indicator_description="Merchandize export earning in million USD", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_16.save()
    indicator_17_17 = Indicator(indicator_name="17.17 Service export earning in million USD", indicator_goal=goal_17, indicator_description="Service export earning in million USD", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_17.save()
    indicator_17_18 = Indicator(indicator_name="17.18 Macroeconomic Dashboard (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Macroeconomic Dashboard (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_18.save()
    indicator_17_19 = Indicator(indicator_name="17.19 Mechanisms in place to enhance policy coherence of sustainable development (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Mechanisms in place to enhance policy coherence of sustainable development (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_19.save()
    indicator_17_20 = Indicator(indicator_name="17.20 Extent of use of country-owned results frameworks and planning tools by providers of development cooperation (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Extent of use of country-owned results frameworks and planning tools by providers of development cooperation (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_20.save()
    indicator_17_21 = Indicator(indicator_name="17.21 Reporting progress in multi-stakeholder development effectiveness monitoring frameworks that support the achievement of the sustainable development goals (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Reporting progress in multi-stakeholder development effectiveness monitoring frameworks that support the achievement of the sustainable development goals (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_21.save()
    indicator_17_22 = Indicator(indicator_name="17.22 Statistical capacity indicator for Sustainable Development Goal monitoring (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Statistical capacity indicator for Sustainable Development Goal monitoring (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_22.save()
    indicator_17_23 = Indicator(indicator_name="17.23 Countries with national statistical legislation exists that complies with", indicator_goal=goal_17, indicator_description="the Fundamental Principles of Official Statistics (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_23.save()
    indicator_17_24 = Indicator(indicator_name="17.24 Countries with national statistical plans with funding from Government (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Countries with national statistical plans with funding from Government (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_24.save()
    indicator_17_25 = Indicator(indicator_name="17.25 Countries that have conducted at least one population and housing census in the last 10 years (1 = YES; 0 = NO)", indicator_goal=goal_17, indicator_description="Countries that have conducted at least one population and housing census in the last 10 years (1 = YES; 0 = NO)", long_term_objective="By 2030, ...", recorded_by=user)
    indicator_17_25.save()
    print("Indicator 17 added successfully")
    #here........
    print("DONE! You can now run the server.")


main()